### ISSUE TITLE
In output. marvel.json has star_wars data. 

### ISSUE THREAD

**Issue by BurdujaAdrian** [domeeno/oop-course-repo#3]
![image](https://github.com/user-attachments/assets/845c7835-6504-4130-a3d2-52d7988ae57a)

**Comment by MihaelaCatan04** [comment]
That is the output of the template and since there is no classification algorithm implemented in the template, of course the program returned starwars data in marvel.json.

**Comment by BurdujaAdrian** [comment]
> That is the output of the template and since there is no classification algorithm implemented in the template, of course the program returned starwars data in marvel.json.

Yeah but it's the correct data for test-input.json. it's clearly a simple mistake

**Comment by domeeno** [comment]
It is a coding mistake, a fix will be provided and the issue will be closed. Good job noticing it. Your contribution is really appreciated.

**Comment by domeeno** [comment]
Fixed
